// This file was automatically generated by Typical 0.12.1.
// Visit https://github.com/stepchowfun/typical for more information.

use std::{
    cmp::min,
    io::{self, BufRead, Error, ErrorKind, Write},
    mem::transmute,
};

const MISSING_FIELDS_ERROR_MESSAGE: &str = "Struct missing one or more required field(s).";

pub trait Serialize {
    fn size(&self) -> usize;

    fn serialize<T: Write>(&self, writer: T) -> io::Result<()>;
}

pub trait Deserialize: Sized {
    fn deserialize<T: BufRead>(reader: T) -> io::Result<Self>;
}

fn zigzag_encode(value: i64) -> u64 {
    unsafe { transmute::<i64, u64>(value >> 63_u32) ^ transmute::<i64, u64>(value << 1_u32) }
}

fn zigzag_decode(value: u64) -> i64 {
    unsafe { transmute::<u64, i64>(value >> 1_u32) ^ -transmute::<u64, i64>(value & 1) }
}

fn varint_size_from_value(value: u64) -> usize {
    match value {
        0_u64..=127_u64 => 1,
        128_u64..=16_511_u64 => 2,
        16_512_u64..=2_113_663_u64 => 3,
        2_113_664_u64..=270_549_119_u64 => 4,
        270_549_120_u64..=34_630_287_487_u64 => 5,
        34_630_287_488_u64..=4_432_676_798_591_u64 => 6,
        4_432_676_798_592_u64..=567_382_630_219_903_u64 => 7,
        567_382_630_219_904_u64..=72_624_976_668_147_839_u64 => 8,
        72_624_976_668_147_840_u64..=18_446_744_073_709_551_615_u64 => 9,
    }
}

fn varint_size_from_first_byte(first_byte: u8) -> u32 {
    first_byte.trailing_zeros() + 1
}

fn serialize_varint<T: Write>(mut value: u64, writer: &mut T) -> io::Result<()> {
    match value {
        0_u64..=127_u64 => writer.write_all(&[((value << 1_u32) as u8) | 0b0000_0001]),
        128_u64..=16_511_u64 => {
            value -= 128_u64;
            writer.write_all(&[
                ((value << 2_u32) as u8) | 0b0000_0010,
                (value >> 6_u32) as u8,
            ])
        }
        16_512_u64..=2_113_663_u64 => {
            value -= 16_512_u64;
            writer.write_all(&[
                ((value << 3_u32) as u8) | 0b0000_0100,
                (value >> 5_u32) as u8,
                (value >> 13_u32) as u8,
            ])
        }
        2_113_664_u64..=270_549_119_u64 => {
            value -= 2_113_664_u64;
            writer.write_all(&[
                ((value << 4_u32) as u8) | 0b0000_1000,
                (value >> 4_u32) as u8,
                (value >> 12_u32) as u8,
                (value >> 20_u32) as u8,
            ])
        }
        270_549_120_u64..=34_630_287_487_u64 => {
            value -= 270_549_120_u64;
            writer.write_all(&[
                ((value << 5_u32) as u8) | 0b0001_0000,
                (value >> 3_u32) as u8,
                (value >> 11_u32) as u8,
                (value >> 19_u32) as u8,
                (value >> 27_u32) as u8,
            ])
        }
        34_630_287_488_u64..=4_432_676_798_591_u64 => {
            value -= 34_630_287_488_u64;
            writer.write_all(&[
                ((value << 6_u32) as u8) | 0b0010_0000,
                (value >> 2_u32) as u8,
                (value >> 10_u32) as u8,
                (value >> 18_u32) as u8,
                (value >> 26_u32) as u8,
                (value >> 34_u32) as u8,
            ])
        }
        4_432_676_798_592_u64..=567_382_630_219_903_u64 => {
            value -= 4_432_676_798_592_u64;
            writer.write_all(&[
                ((value << 7_u32) as u8) | 0b0100_0000,
                (value >> 1_u32) as u8,
                (value >> 9_u32) as u8,
                (value >> 17_u32) as u8,
                (value >> 25_u32) as u8,
                (value >> 33_u32) as u8,
                (value >> 41_u32) as u8,
            ])
        }
        567_382_630_219_904_u64..=72_624_976_668_147_839_u64 => {
            value -= 567_382_630_219_904_u64;
            writer.write_all(&[
                0b1000_0000,
                value as u8,
                (value >> 8_u32) as u8,
                (value >> 16_u32) as u8,
                (value >> 24_u32) as u8,
                (value >> 32_u32) as u8,
                (value >> 40_u32) as u8,
                (value >> 48_u32) as u8,
            ])
        }
        72_624_976_668_147_840_u64..=18_446_744_073_709_551_615_u64 => {
            value -= 72_624_976_668_147_840_u64;
            writer.write_all(&[
                0b0000_0000,
                value as u8,
                (value >> 8_u32) as u8,
                (value >> 16_u32) as u8,
                (value >> 24_u32) as u8,
                (value >> 32_u32) as u8,
                (value >> 40_u32) as u8,
                (value >> 48_u32) as u8,
                (value >> 56_u32) as u8,
            ])
        }
    }
}

fn deserialize_varint<T: BufRead>(reader: &mut T) -> io::Result<u64> {
    let mut first_byte_buffer = [0; 1];
    reader.read_exact(&mut first_byte_buffer[..])?;
    let first_byte = first_byte_buffer[0];
    let size_minus_one = first_byte.trailing_zeros();

    let mut remaining_bytes_buffer = [0; 8];
    reader.read_exact(&mut remaining_bytes_buffer[0..size_minus_one as usize])?;
    let remaining_bytes_value = u64::from_le_bytes(remaining_bytes_buffer);

    match size_minus_one {
        0 => Ok(u64::from(first_byte >> 1_u32)),
        1 => Ok(128_u64 + u64::from(first_byte >> 2_u32) + (remaining_bytes_value << 6_u32)),
        2 => Ok(16_512_u64 + u64::from(first_byte >> 3_u32) + (remaining_bytes_value << 5_u32)),
        3 => Ok(2_113_664_u64 + u64::from(first_byte >> 4_u32) + (remaining_bytes_value << 4_u32)),
        4 => {
            Ok(270_549_120_u64 + u64::from(first_byte >> 5_u32) + (remaining_bytes_value << 3_u32))
        }
        5 => Ok(34_630_287_488_u64
            + u64::from(first_byte >> 6_u32)
            + (remaining_bytes_value << 2_u32)),
        6 => Ok(4_432_676_798_592_u64
            + u64::from(first_byte >> 7_u32)
            + (remaining_bytes_value << 1_u32)),
        7 => Ok(567_382_630_219_904_u64 + remaining_bytes_value),
        _ => Ok(72_624_976_668_147_840_u64.wrapping_add(remaining_bytes_value)),
    }
}

fn field_header_size(index: u64, payload_size: usize, integer_encoded: bool) -> usize {
    match payload_size {
        0 => varint_size_from_value((index << 2_u32) | 0b00),
        8 => varint_size_from_value((index << 2_u32) | 0b01),
        size => {
            if integer_encoded {
                varint_size_from_value((index << 2_u32) | 0b10)
            } else {
                varint_size_from_value((index << 2_u32) | 0b11)
                    + varint_size_from_value(size as u64)
            }
        }
    }
}

fn serialize_field_header<T: Write>(
    writer: &mut T,
    index: u64,
    payload_size: usize,
    integer_encoded: bool,
) -> io::Result<()> {
    match payload_size {
        0 => serialize_varint((index << 2_u32) | 0b00, writer),
        8 => serialize_varint((index << 2_u32) | 0b01, writer),
        size => {
            if integer_encoded {
                serialize_varint((index << 2_u32) | 0b10, writer)
            } else {
                serialize_varint((index << 2_u32) | 0b11, writer)?;
                serialize_varint(size as u64, writer)
            }
        }
    }
}

fn deserialize_field_header<T: BufRead>(reader: &mut T) -> io::Result<(u64, usize)> {
    let tag = deserialize_varint(&mut *reader)?;

    let index = tag >> 2_u32;

    let size = match tag & 0b11 {
        0b00 => 0,
        0b01 => 8,
        0b10 => {
            let buffer = (&mut *reader).fill_buf()?;

            if buffer.is_empty() {
                return Err(Error::new(
                    ErrorKind::UnexpectedEof,
                    "Error decoding field.",
                ));
            }

            varint_size_from_first_byte(buffer[0]) as usize
        }
        _ => deserialize_varint(&mut *reader)? as usize,
    };

    Ok((index, size))
}

fn skip<T: BufRead>(reader: &mut T, mut amount: usize) -> io::Result<()> {
    while amount > 0 {
        let buffer = reader.fill_buf()?;
        let num_bytes_to_consume = min(buffer.len(), amount);
        reader.consume(num_bytes_to_consume);
        amount -= num_bytes_to_consume;
    }

    Ok(())
}

fn finish<T: BufRead>(reader: &mut T) -> io::Result<()> {
    loop {
        let buffer = reader.fill_buf()?;

        if buffer.is_empty() {
            return Ok(());
        }

        let buffer_size = buffer.len();
        reader.consume(buffer_size);
    }
}

pub mod empty {
}
